[build]
  command = "npm run build"
  publish="build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BUDGET_APP_BLOG = https://greenprint-strapi-server.herokuapp.com
  REACT_APP_BUDGET_APP_SERVER = https://greenprint-2020-server.herokuapp.com